# Generated by Django 3.0.2 on 2022-06-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0003_auto_20220624_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
