# Generated by Django 3.0.2 on 2022-06-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0005_adminmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=800, null=True)),
            ],
            options={
                'ordering': ['project'],
            },
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=800, null=True)),
            ],
            options={
                'ordering': ['skill'],
            },
        ),
    ]
