# Generated by Django 3.0.2 on 2022-06-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0007_auto_20220625_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['rollno']},
        ),
        migrations.RemoveField(
            model_name='students',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='students',
            name='skills',
        ),
    ]
