# Generated by Django 3.0.2 on 2022-06-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0009_auto_20220625_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='custommail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
