# Generated by Django 3.0.2 on 2022-07-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0014_auto_20220715_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooksmodel',
            name='pdf',
            field=models.FileField(default=' ', upload_to='pdfs/'),
        ),
    ]
